/*
 * (c) Copyright Ascensio System SIA 2026
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.client.model.ApiDateTime;
import org.openapitools.client.model.EditHistoryAuthor;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;

import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * The parameters of the file editing history.
 */
@JsonPropertyOrder({
  EditHistoryChangesWrapper.JSON_PROPERTY_USER,
  EditHistoryChangesWrapper.JSON_PROPERTY_CREATED,
  EditHistoryChangesWrapper.JSON_PROPERTY_DOCUMENT_SHA256
})

public class EditHistoryChangesWrapper {
  public static final String JSON_PROPERTY_USER = "user";
  @javax.annotation.Nullable  private EditHistoryAuthor user;

  public static final String JSON_PROPERTY_CREATED = "created";
  @javax.annotation.Nullable  private ApiDateTime created;

  public static final String JSON_PROPERTY_DOCUMENT_SHA256 = "documentSha256";
  @javax.annotation.Nullable  private JsonNullable<String> documentSha256 = JsonNullable.<String>undefined();

  public EditHistoryChangesWrapper() {
  }


  public EditHistoryChangesWrapper user(@javax.annotation.Nullable EditHistoryAuthor user) {
    
    this.user = user;
    return this;
  }

  /**
   * Get user
   * @return user
   */
  @javax.annotation.Nullable  @JsonProperty(value = JSON_PROPERTY_USER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EditHistoryAuthor getUser() {
    return user;
  }


  @JsonProperty(value = JSON_PROPERTY_USER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUser(@javax.annotation.Nullable EditHistoryAuthor user) {
    this.user = user;
  }

  public EditHistoryChangesWrapper created(@javax.annotation.Nullable ApiDateTime created) {
    
    this.created = created;
    return this;
  }

  /**
   * Get created
   * @return created
   */
  @javax.annotation.Nullable  @JsonProperty(value = JSON_PROPERTY_CREATED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ApiDateTime getCreated() {
    return created;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreated(@javax.annotation.Nullable ApiDateTime created) {
    this.created = created;
  }

  public EditHistoryChangesWrapper documentSha256(@javax.annotation.Nullable String documentSha256) {
    this.documentSha256 = JsonNullable.<String>of(documentSha256);
    
    return this;
  }

  /**
   * The document hash generated by the SHA-256 algorithm.
   * @return documentSha256
   */
  @javax.annotation.Nullable  @JsonIgnore

  public String getDocumentSha256() {
        return documentSha256.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_DOCUMENT_SHA256, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<String> getDocumentSha256_JsonNullable() {
    return documentSha256;
  }
  
  @JsonProperty(JSON_PROPERTY_DOCUMENT_SHA256)
  public void setDocumentSha256_JsonNullable(JsonNullable<String> documentSha256) {
    this.documentSha256 = documentSha256;
  }

  public void setDocumentSha256(@javax.annotation.Nullable String documentSha256) {
    this.documentSha256 = JsonNullable.<String>of(documentSha256);
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EditHistoryChangesWrapper editHistoryChangesWrapper = (EditHistoryChangesWrapper) o;
    return Objects.equals(this.user, editHistoryChangesWrapper.user) &&
        Objects.equals(this.created, editHistoryChangesWrapper.created) &&
        equalsNullable(this.documentSha256, editHistoryChangesWrapper.documentSha256);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(user, created, hashCodeNullable(documentSha256));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EditHistoryChangesWrapper {\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    documentSha256: ").append(toIndentedString(documentSha256)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `user` to the URL query string
    if (getUser() != null) {
      joiner.add(getUser().toUrlQueryString(prefix + "user" + suffix));
    }

    // add `created` to the URL query string
    if (getCreated() != null) {
      joiner.add(getCreated().toUrlQueryString(prefix + "created" + suffix));
    }

    // add `documentSha256` to the URL query string
    if (getDocumentSha256() != null) {
      try {
        joiner.add(String.format("%sdocumentSha256%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getDocumentSha256()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    return joiner.toString();
  }

}

