/*
 * (c) Copyright Ascensio System SIA 2026
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;

import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * An object that is generated by the integrator to uniquely identify a file in its system.
 */
@JsonPropertyOrder({
  FileReferenceData.JSON_PROPERTY_FILE_KEY,
  FileReferenceData.JSON_PROPERTY_INSTANCE_ID,
  FileReferenceData.JSON_PROPERTY_ROOM_ID,
  FileReferenceData.JSON_PROPERTY_CAN_EDIT_ROOM
})

public class FileReferenceData {
  public static final String JSON_PROPERTY_FILE_KEY = "fileKey";
  @javax.annotation.Nullable  private JsonNullable<String> fileKey = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_INSTANCE_ID = "instanceId";
  @javax.annotation.Nullable  private JsonNullable<String> instanceId = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_ROOM_ID = "roomId";
  @javax.annotation.Nullable  private JsonNullable<String> roomId = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_CAN_EDIT_ROOM = "canEditRoom";
  @javax.annotation.Nullable  private Boolean canEditRoom;

  public FileReferenceData() {
  }


  public FileReferenceData fileKey(@javax.annotation.Nullable String fileKey) {
    this.fileKey = JsonNullable.<String>of(fileKey);
    
    return this;
  }

  /**
   * The unique document identifier used by the service to get a link to the file.
   * @return fileKey
   */
  @javax.annotation.Nullable  @JsonIgnore

  public String getFileKey() {
        return fileKey.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_FILE_KEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<String> getFileKey_JsonNullable() {
    return fileKey;
  }
  
  @JsonProperty(JSON_PROPERTY_FILE_KEY)
  public void setFileKey_JsonNullable(JsonNullable<String> fileKey) {
    this.fileKey = fileKey;
  }

  public void setFileKey(@javax.annotation.Nullable String fileKey) {
    this.fileKey = JsonNullable.<String>of(fileKey);
  }

  public FileReferenceData instanceId(@javax.annotation.Nullable String instanceId) {
    this.instanceId = JsonNullable.<String>of(instanceId);
    
    return this;
  }

  /**
   * The unique system identifier.
   * @return instanceId
   */
  @javax.annotation.Nullable  @JsonIgnore

  public String getInstanceId() {
        return instanceId.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_INSTANCE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<String> getInstanceId_JsonNullable() {
    return instanceId;
  }
  
  @JsonProperty(JSON_PROPERTY_INSTANCE_ID)
  public void setInstanceId_JsonNullable(JsonNullable<String> instanceId) {
    this.instanceId = instanceId;
  }

  public void setInstanceId(@javax.annotation.Nullable String instanceId) {
    this.instanceId = JsonNullable.<String>of(instanceId);
  }

  public FileReferenceData roomId(@javax.annotation.Nullable String roomId) {
    this.roomId = JsonNullable.<String>of(roomId);
    
    return this;
  }

  /**
   * Room ID
   * @return roomId
   */
  @javax.annotation.Nullable  @JsonIgnore

  public String getRoomId() {
        return roomId.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_ROOM_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<String> getRoomId_JsonNullable() {
    return roomId;
  }
  
  @JsonProperty(JSON_PROPERTY_ROOM_ID)
  public void setRoomId_JsonNullable(JsonNullable<String> roomId) {
    this.roomId = roomId;
  }

  public void setRoomId(@javax.annotation.Nullable String roomId) {
    this.roomId = JsonNullable.<String>of(roomId);
  }

  public FileReferenceData canEditRoom(@javax.annotation.Nullable Boolean canEditRoom) {
    
    this.canEditRoom = canEditRoom;
    return this;
  }

  /**
   * Specifies if the room can be edited out or not.
   * @return canEditRoom
   */
  @javax.annotation.Nullable  @JsonProperty(value = JSON_PROPERTY_CAN_EDIT_ROOM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCanEditRoom() {
    return canEditRoom;
  }


  @JsonProperty(value = JSON_PROPERTY_CAN_EDIT_ROOM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCanEditRoom(@javax.annotation.Nullable Boolean canEditRoom) {
    this.canEditRoom = canEditRoom;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FileReferenceData fileReferenceData = (FileReferenceData) o;
    return equalsNullable(this.fileKey, fileReferenceData.fileKey) &&
        equalsNullable(this.instanceId, fileReferenceData.instanceId) &&
        equalsNullable(this.roomId, fileReferenceData.roomId) &&
        Objects.equals(this.canEditRoom, fileReferenceData.canEditRoom);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(fileKey), hashCodeNullable(instanceId), hashCodeNullable(roomId), canEditRoom);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FileReferenceData {\n");
    sb.append("    fileKey: ").append(toIndentedString(fileKey)).append("\n");
    sb.append("    instanceId: ").append(toIndentedString(instanceId)).append("\n");
    sb.append("    roomId: ").append(toIndentedString(roomId)).append("\n");
    sb.append("    canEditRoom: ").append(toIndentedString(canEditRoom)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `fileKey` to the URL query string
    if (getFileKey() != null) {
      try {
        joiner.add(String.format("%sfileKey%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getFileKey()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `instanceId` to the URL query string
    if (getInstanceId() != null) {
      try {
        joiner.add(String.format("%sinstanceId%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getInstanceId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `roomId` to the URL query string
    if (getRoomId() != null) {
      try {
        joiner.add(String.format("%sroomId%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getRoomId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `canEditRoom` to the URL query string
    if (getCanEditRoom() != null) {
      try {
        joiner.add(String.format("%scanEditRoom%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCanEditRoom()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    return joiner.toString();
  }

}

